### ISSUE TITLE
[Regression] postRecord overrides RequestProperties in narumi

### ISSUE THREAD

**Issue by et1975** [fable-compiler/fable-powerpack#11]
So does patch, I imagine.

The specific use case is authentication header, but it would be true for any property: the merge of passed and default properties needs to prefer passed properties and use default only if not set explicitly (I could see myself using specific `content-type`, for example, even if serialization method is json).

**Comment by alfonsogarciacaro** [comment]
Could you please try if this gets fixed by changing [this line](https://github.com/fable-compiler/fable-powerpack/blob/1b7f597ff26ecf2a42ee3d42d70da60cdb7de888/src/Fetch.fs#L377) to `|> List.append <| properties`?
