### ISSUE TITLE
Documents required.

### ISSUE THREAD

**Issue by kunjee17** [fable-compiler/fable-powerpack#13]
A little document to do simple things would be good. As Fable is reaching 1.0 and not everyone like to read test cases. I guess document will surely help.

**Comment by ryukinix** [comment]
I agreed.

**Comment by kunjee17** [comment]
Something inline with [Elimsh bulma](https://mangelmaxime.github.io/Fable.Elmish.Bulma/) would be great.

**Comment by ryukinix** [comment]
Actually we have any example about  how most of the functions from Fable.Powerpack works? I'm searching about a simple usage of Fetch API using promises with F# types and I'm trouble. 

Would be awesome a detailed documentation.

**Comment by StachuDotNet** [comment]
Perhaps a dumb question, but have you checked out the tests?
https://github.com/fable-compiler/fable-powerpack/tree/master/tests

**Comment by ryukinix** [comment]
I only saw #29 now (referring the PR)

**Comment by MangelMaxime** [comment]
Hello, you can take a look at the tests and the PR you linked.  If you miss something toi can explain it here or in the PR 😊

**Comment by ryukinix** [comment]
Yes, thanks for pointing that! Is a great start. If I have some doubts I'll really ask.

Great job!

**Comment by alfonsogarciacaro** [comment]
Documentation can be found here thanks to @MangelMaxime! http://fable.io/fable-powerpack/

PRs to improve the docs are more than welcome, you only need to edit the markdown files in `docs/posts`.

**Comment by kunjee17** [comment]
Thanks @MangelMaxime . Nice docs.
