### ISSUE TITLE
a non-beta release

### ISSUE THREAD

**Issue by et1975** [fable-compiler/fable-powerpack#15]
Now that Fable is out of beta, PowerPack is the only "dev" release at this point that prevents me from publishing my packages as "stable" as well.

**Comment by alfonsogarciacaro** [comment]
Now it's time for some repo cleaning! I merged the nuget branch with master and published 1.1.0. I just noticed now we have a dependency on Fable.Import.Browser but I guess that's ok. Crossing fingers so everything works fine (it did pass the tests) 🤞 

I'll publish a non-beta release of Fable.React tomorrow too.
