### ISSUE TITLE
Can’t understand what is the easy way to add custom headers in Fable.PowerPack.Fetch

### ISSUE THREAD

**Issue by ed-ilyin** [fable-compiler/fable-powerpack#19]
Sorry for noob question: what is the easy way to add custom headers in Fable.PowerPack.Fetch?

**Comment by alfonsogarciacaro** [comment]
Here's an example, I hope it helps 😄 

```fsharp
  GlobalFetch.fetch(
    RequestInfo.Url url,
    requestProps
      [ RequestProperties.Method HttpMethod.POST
        requestHeaders [ContentType "application/json"]
        RequestProperties.Body !^(toJson myObject) ])
```

fable-powerpack contains helpers for most common cases [like this one](https://github.com/fable-compiler/fable-powerpack/blob/b035313b7376922446d51e503ef2913ef41d2172/src/Fetch.fs#L370-L380). You can also check [the tests](https://github.com/fable-compiler/fable-powerpack/blob/b035313b7376922446d51e503ef2913ef41d2172/tests/FetchTests.fs).

**Comment by ed-ilyin** [comment]
I have no problems with predefined headers, but still not clear how to add custom headers.
Tests and code does not have examples.
This does not work:
```
        let headers =
            [   ContentType "application/x-www-form-urlencoded"
                "API-Key", Json.Encode.string apiKey
                "API-Sign", signature
            ]
```

**Comment by MangelMaxime** [comment]
@ed-ilyin Can you try something like that:

```fs
      let headers =  
            [   ContentType "application/x-www-form-urlencoded"
                !!("API-Key", Json.Encode.string apiKey)
                !!("API-Sign", signature)
            ]
```

`!!` comes from `Fable.Core.JsInterop`

I am not sure if this will work, but I saw people using this synthax for custom data attribute in Elmish and it's kind the same situation.
To explain, `!!` is equivalent to `unbox(".....", "......")` so it's simply make the compiler happy and Fable should convert the Key/Value into the desired object.

**Comment by alfonsogarciacaro** [comment]
Sorry @ed-ilyin, I misread the issue 😅 Thanks for the explanation, @MangelMaxime! That's right, you can use dynamic casting to fake a key-value pair when passing values to `keyValueList`. Another alternative is to add a union case with `Erase` attribute to the union type.

```fsharp
| [<Erase>] Custom of key:string * value:obj
```

Then you can do:

```fsharp
      let headers =  
            [   ContentType "application/x-www-form-urlencoded"
                Custom("API-Key", Json.Encode.string apiKey)
                // Same as !!("API-Key", Json.Encode.string apiKey) but typed
            ]
```

I just noticed the `Erase` attribute is not working in these cases in the current release, but I've fixed that for the next one. Also, please not the CaseRules (like `LowerFirst` letter) don't apply for custom headers.

**Comment by ed-ilyin** [comment]
I like the idea with Custom case. Should I create PR?

**Comment by alfonsogarciacaro** [comment]
Yes, please :)

**Comment by ed-ilyin** [comment]
PR is created: https://github.com/fable-compiler/fable-powerpack/pull/20
