### ISSUE TITLE
Make `Promise.catch` and `Promise.catchBind` emit "$0.then" to make it compatible with ad-hoc implementations

### ISSUE THREAD

**Issue by fsoikin** [fable-compiler/fable-powerpack#26]
Currently `Promise.catch` and `Promise.catchBind` emit `$1.catch($0)`. This is the only point where anything except `then` is used, and this makes PowerPack's promises incompatible with minimal implementations, such as VSCode's [`Thenable`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L5568).

This, in turn, forces us to do a conversion (aka "wrapper") when interacting with VSCode, which could be unnecessary if only PowerPack's `Promise` relied solely on `then`, in which case just a dirty cast `!!x` would be sufficient.

The proposal is to make `Promise.catch` and `Promise.catchBind` emit `$1.then(undefined, $0)` (per [the spec](http://www.ecma-international.org/ecma-262/6.0/#sec-promise.prototype.catch)) instead of the current `$1.catch($0)`.

**Comment by fsoikin** [comment]
Note: I'm not completely sure that this is a good idea. Requesting feedback.

**Comment by MangelMaxime** [comment]
I believe promise implementation support catch un JS. 

If i am right I don't think it's a good idea to change the implementation because Vscode doesn't support the standard.

**Comment by MangelMaxime** [comment]
Also `catch` don't have the same signification than `then`
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Promise/catch

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime The link actually says `.catch(onRejected)` is the same as `.then(undefined, onRejected)` :wink:

@fsoikin I'm not opposed to this. If something, maybe use `void 0` instead, as it's considered safer in case the `undefined` global variable has been, well, defined 😄

**Comment by MangelMaxime** [comment]
Ah yes, sorry I didn't saw the `Emit` in the PR :)
