### ISSUE TITLE
Retrieving object when Promise fails.

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/fable-powerpack#35]
Hi!

I'm currently working with [PouchDB](https://pouchdb.com/api.html#create_document) a JS based NoSQL browser database.
When inserting a new record I use promises:

```f#
    promise {
      let! r= db.put(o)
      return r
    }
    |> Fable.PowerPack.Promise.map(fun response -> handler (Load response))
```

When this fails, PouchDB sends back an object with some interesting information, for instance the error status which would allow me to create a custom handler:

![image](https://user-images.githubusercontent.com/883207/34117805-181ca888-e41d-11e7-85ab-55c5d33f33fd.png)

How can I get this object using `Fable.PowerPack.Promise.catch` ? Is it possible?
Thanks!

**Comment by alfonsogarciacaro** [comment]
Is `Fable.PowerPack.Promise.catch` not working? Did you use it like this?

```fsharp
    promise {
      let! r= db.put(o)
      return r
    }
    |> Promise.map(fun response -> handler (Load response))
    |> Promise.catch(fun ex -> (* Handle error here *) )
```

[There are also other catch methods](https://github.com/fable-compiler/fable-powerpack/blob/06593dc9bd3a1cc0a4df915b11cf37d521ed3bd7/src/Promise.fs#L34-L52) and you can also use try ... with inside the `promise` computation expression:

```fsharp
promise {
  try
      let! r = db.put(o)
      let x = handler (Load r)
      return x
  with ex ->
     // Deal with error here
}
```

See also https://github.com/fable-compiler/fable-powerpack/pull/34#issuecomment-348426421

**Comment by whitetigle** [comment]
Sorry my message was not clear. 
So yes `Fable.PowerPack.Promise.catch` works like you mentionned. 👍 

But PouchDB sends an object with some custom information when it fails (see screenshot). So sow do I get access to these information? 

Certainly a noob question here. or maybe i'm 😫. But I fail to see how I can do this.

**Comment by whitetigle** [comment]
In fact I was hoping to be able to use something like [Exception.Data](https://msdn.microsoft.com/en-us/library/system.exception.data(v=vs.110).aspx)

but it fails: `error FABLE: Cannot find replacement for System.Exception::get_Data`

**Comment by whitetigle** [comment]
So I was absolutely tired 😩. Answer was: `let x = exception.ToString()` Definitely time to stop coding for today.

Sorry!

**Comment by alfonsogarciacaro** [comment]
Haha, no worries. Yeah, it's tricky because in .NET you can **only** throw exceptions but in JS you **usually** throw `Error` (mapped to Exception by Fable) but you can also throw anything else. Most of Fable libraries assume Errors, but for example the `Promise.either` function accepts anything for the fail continuation.

You can also use the dynamic operators to access the fields of the error object (`ex?name`) or if you define an interface you can also use dynamic casting:

```fsharp

type PouchDBError =
  abstract status: int
  name: string
  message: string
  error: bool

// Your code here
|> Promise.catch (fun ex ->
  let ex: PouchDBError = !!ex
  // Now you can access the fields
)
```

**Comment by MangelMaxime** [comment]
Oh I never think of using `unbox` + a type de get intellisense on this cases.

If the error format is not always the same or have optional fields, you can also use Thot.Json in this cases to avoid runtime errors.

**Comment by whitetigle** [comment]
Thanks @alfonsogarciacaro for the hints.
Before you answered I went with 
`let err : PouchDBError = ofJson<PouchDBError > (o.ToString())`
but
`let ex: PouchDBError = !!ex`
is certainly faster 😉 


> you can also use Thot.Json in this cases to avoid runtime errors. 

Kudos to the author of this new great library 🙌 . So now it will be FEFT: Fable + Elmish + Fulma + Thot 😉
