### ISSUE TITLE
Extending Date.Local? 

### ISSUE THREAD

**Issue by AkosLukacs** [fable-compiler/fable-powerpack#38]
Hi, this is a question / suggestion about adding more data to Date.Local:
 - date format string (and maybe time, date - time format strings)
 - start of week (it's Monday here, used in date picker UIs for example)

Opinions? Go for it? I guess I can do it for the current locales.

**Comment by MangelMaxime** [comment]
Seems like a good idea.

We could transform into something like:

```fs
type Date =
    { Months : Months
      AbbreviatedMonths : Months
      Days : DaysOfWeek
      AbbreviatedDays : DaysOfWeek
      DefaultFormat : string
      FirstDayOfTheWeek : int }

type Time =
    { AM : string
      PM : string
      DefaultFormat : string }
```

I am not sure about `FirstDayOfTheWeek` type. We need to test, to use in Fulma.Elmish.DatePicker first to check int is the right type or no.

Access API would be: `french.Date.DefaultFormat`

**Comment by alfonsogarciacaro** [comment]
If we're making breaking changes, maybe we could turn the language options (french, russian...) into functions instead of values. Tree shaking should work with values too, but if `Local.fs` grows too big, probably using "pure" functions like `getFrench()` will make it easier for UglifyJS or similar tools to remove the unused code.

**Comment by MangelMaxime** [comment]
If we are making breaking changes, we should probably reverse the args order:

From: `let localFormat (local : Localization) (date : DateTime) formatString =`

To: `let localFormat (local : Localization) formatString (date : DateTime) =`

This would allow user to chain the function, or make alias function more easily with partial application, etc.

**Comment by AkosLukacs** [comment]
Hi, 

Two questions:

 - `FirstDayOfTheWeek` -> Sunday is 0, Monday is 1?
 -  At the end of [Format.fs](https://github.com/fable-compiler/fable-powerpack/blob/a68f083be3b748e04911a81295ad4230d4e95b49/src/Date/Format.fs#L97) the line `let format (date : DateTime) formatString = localFormat Local.english date formatString` defaults to english, and is used in the tests. Is this meant to be part of the public API? If so, should I change the parameter order to `let format formatString (date : DateTime) = ...` to allow partial application? Or just move it to the tests?

And found an issue:

The date format and first day of the week in the US and UK differs. Looks like UK uses `d/M/yyyy` and weeks start on Monday, but US uses `M/d/yyyy` and weeks start on Sunday. So just "english" is not enough. Don't know, separate the `english` locale to `englishUk` and `englishUs`? (or `getEnglishUk()` and `getEnglishUs()` if we switch to functions)

Also, not sure about including default time format:
 - It's not used anywhere yet
 - Multiple use in the same country (at least in the US and UK as far as I know, they use 12 and 24h formats so don't know which one should be the default. Everybody should just use ISO 8601 :) )

And sorry for the late reply...

**Comment by AkosLukacs** [comment]
Hi, what do you think about splitting the `english` locale to UK and US versions?

The date format and first day of the week in the US and UK differs. Looks like UK uses d/M/yyyy and weeks start on Monday, but US uses M/d/yyyy and weeks start on Sunday. So just "english" is not enough. Don't know, separate the english locale to englishUk and englishUs?

**Comment by MangelMaxime** [comment]
- Sunday is 0 indeed.
- Yes we can split the english locale in two parts

**Comment by AkosLukacs** [comment]
Oh, and what about the default `format` in [Format.fs](https://github.com/fable-compiler/fable-powerpack/blob/b37e807becad81ce6ed3e09a7cea3e19f00cdf3c/src/Date/Format.fs#L97)? Should that default to US or UK locale?
Or make another breaking change, and remove the "default", since users can make their default easily enought?

**Comment by MangelMaxime** [comment]
I think I am in favor of making thing explicit by forcing the user to select it's locale. This is something I am trying to do in my libraries now and I found it easier to write maintainable code, etc..

@alfonsogarciacaro What do you think ?

**Comment by alfonsogarciacaro** [comment]
Yes, I agree it's better to pass the locale as explicit argument. Even if it's a breaking change, users should be able to fix it quickly looking at the new signature when the compiler warns them.
