### ISSUE TITLE
Fetch with Fable 2: wrong ContentType header?

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/fable-powerpack#62]
Hi,
I have been struggling to send some json data through a POST request using Fetch from a fable 2 project.

```f#
      let withProps body=
          [
              requestHeaders [ContentType "application/json"]
              RequestProperties.Mode RequestMode.Nocors
              RequestProperties.Body !!body
          ]

      let! result = 
        let props = body |> withProps
        tryPostRecord url body props
```
or 

```f#
    let withProps body=
        [
            RequestProperties.Method HttpMethod.POST
            requestHeaders
              [
                HttpRequestHeaders.ContentType "application/json"
              ]
            RequestProperties.Mode RequestMode.Nocors
            RequestProperties.Body !!body
        ]

    body
      |> withProps
      |> fetch url
      |> Promise.bind (fun res ->
        res.text())
      |> Promise.map (Decode.fromString decoder)
```
However, it seems that whatever the ContentType used, it will revert to `text/plain;charset=UTF-8`.
I never had this problem with any of my Fable 1 projects. 
So maybe I'm missing something? 
Thanks!

**Comment by whitetigle** [comment]
hmm
or maybe maybe... my body is considered as text and the browser is bypassing my ContentType header?

**Comment by MangelMaxime** [comment]
Is [`sendRecord`](https://github.com/fable-compiler/fable-powerpack/blob/master/src/Fetch.fs#L381-L389) set in the correct type ?

**Comment by whitetigle** [comment]
ok found (from stackoverflow).

> Mode is set to no-cors.
> Setting the Content-Type to application/json requires permission from CORS

Will try and tell you :)

**Comment by whitetigle** [comment]
Ok I confirm. I setup CORS on the server and everyhting is working. 
Thanks!
