### ISSUE TITLE
Fetch makes GET request first if called with POST method in case of redirect

### ISSUE THREAD

**Issue by vasily-kirichenko** [fable-compiler/fable-powerpack#64]
```fsharp
let props =
    [ RequestProperties.Method HttpMethod.POST
      requestHeaders [ContentType "application/json"]
      RequestProperties.Credentials RequestCredentials.Sameorigin
      RequestProperties.Body !^ body ]

GlobalFetch.fetch(RequestInfo.Url url, requestProps props)
```

![image](https://user-images.githubusercontent.com/873919/49148936-cf276e80-f319-11e8-8a0d-4d2bc5a48237.png)

The server is a Giraffe one, which makes redirect:
```fsharp
routef "/api/foo/%s" (fun path -> redirectTo false (sprintf "http://localhost:8090/%s" path))
```

It works completely fine against `http://localhost:8090/...` until I added the redirect.

**Comment by alfonsogarciacaro** [comment]
Interesting. The fetch bindings are just using the native fetch API so I don't think this is a problem of powerpack. Although it should be default option, [some answers on the web](https://stackoverflow.com/a/39739894) recommend to use `redirect: "follow"`. Unfortunately, it doesn't seem to be implemented yet in the [Fetch RequestProperties](https://github.com/fable-compiler/fable-powerpack/blob/eed497d6cf6a4384801c1d54fc65df771590906f/src/Fetch.fs#L330). Can you try the following and see if it changes anything?

```fsharp
let props =
    [ RequestProperties.Method HttpMethod.POST
      requestHeaders [ContentType "application/json"]
      RequestProperties.Credentials RequestCredentials.Sameorigin
      RequestProperties.Body !^ body
      !!("redirect", "follow")
    ]

GlobalFetch.fetch(RequestInfo.Url url, requestProps props)
```

**Comment by vasily-kirichenko** [comment]
@alfonsogarciacaro thank you, but I've removed the redirect and call the external service manually.
